### PR TITLE
always using the hybrid version of d2l-polymer-behaviors

### PR DESCRIPTION
**Pull request by dlockhart**

### CODE REVIEW

**Comment by dbatiste** [comment]
Should also be able to ditch the d2l-icons variant.  Not sure if you want to do that or wait till I get to this component.

**Comment by dlockhart** [comment]
Yeah I noticed it, but was worried since it depends on colors and I haven't gone through and updated colors yet that I'd be in trouble. Build failed for a related reason (colors), investigating...

**Comment by dbatiste** [comment]
It may be because the d2l-typography variant that is being included is probably trying to pull in old d2l-colors.

**Comment by dbatiste** [comment]
At the end of the day, it should probably look something like:

https://github.com/BrightspaceUI/menu/blob/dbatiste/hybrid-cleanup/bower.json

**Comment by dlockhart** [comment]
Closing for now to focus on colors first, it's the leafiest leaf node.

**Pull request closed without merging**
